spring.application.name=ullas-blomster-app

# Database forbindelse
spring.datasource.url=jdbc:postgresql://localhost:5432/ullas_blomster_db
spring.datasource.username=blomster_user
spring.datasource.password=blomster_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate indstillinger
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect